apiVersion: apps/v1
kind: Deployment
metadata:
  name: soraka
  labels:
    app: soraka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soraka
  template:
    metadata:
      labels:
        app: soraka
    spec:
      containers:
      - name: soraka
        image: public.ecr.aws/d2l1l3q0/mo4devops:dev
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

